life={
    'animals':{
        'cats':['henri','Grumpy','Lucy'],
        'octopi':{},
        'emus':{}
    },
    'plants':{},
    'other':{}
}
print(life.keys())
print(life['animals'].keys())
print(life['animals']['cats'])